include ~/.cache/wallust/kitty.conf

# ---------- Shell ----------
shell /usr/bin/zsh

# ---------- Font ----------
font_family monospace
font_size 12.0
disable_ligatures never

# ---------- Window ----------
# background #1a1b26
confirm_os_window_close 0

# ---------- Padding ----------
window_padding_width 8

# ---------- Cursor ----------
cursor_shape block
cursor #cdd6f4
cursor_blink_interval 0

# ---------- Selection ----------
selection_background #3b3f51
selection_foreground #cdd6f4

# ---------- Scrolling ----------
scrollback_lines 5000
wheel_scroll_multiplier 5.0

# ---------- Performance ----------
# enable_audio_bell no
repaint_delay 10
input_delay 3

