#!/usr/bin/env bash
# Display mode cycle: all outputs, TV only, or everything except the TV.
#
# Each run advances to the next mode. Temporary Lua monitor overrides are
# loaded by monitors.lua; this avoids `hyprctl eval`, which crashes Hyprland
# 0.56.2 when setting the native Lua monitor `disabled` field.
#
# State file: ~/.local/state/dotfiles/livingroom-mode.lua
#
# TV_DESC comes from the TV's EDID as reported by `hyprctl monitors`.

set -euo pipefail

STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/dotfiles"
STATE_FILE="$STATE_DIR/livingroom-mode.lua"
TV_DESC='desc:Ines GmbH NS55DF710NA21'   # EDID make+model from
                                          # capture-monitor.sh — note the
                                          # EDID reports "Ines GmbH" as the
                                          # make, not "Insignia"

mkdir -p "$STATE_DIR"

# Strip the leading "desc:" so we can match against the raw EDID
# description returned by `hyprctl -j monitors .description`.
tv_prefix="${TV_DESC#desc:}"

get_tv_name() {
    hyprctl -j monitors all | jq -r --arg p "$tv_prefix" \
        '.[] | select(.description | startswith($p)) | .name' \
        | head -1
}

# Names of every connected output that ISN'T the TV.
list_non_tv_outputs() {
    hyprctl -j monitors all | jq -r --arg p "$tv_prefix" \
        '.[] | select((.description | startswith($p)) | not) | .name'
}

tv=$(get_tv_name || true)
if [[ -z "$tv" ]]; then
    echo "livingroom-mode: TV not found (looking for '$TV_DESC')" >&2
    echo "  - is the TV plugged in?" >&2
    echo "  - different TV? update TV_DESC in this script;" >&2
    echo "    hypr/scripts/capture-monitor.sh prints its desc" >&2
    exit 1
fi

if [[ ! -f "$STATE_FILE" ]]; then
    mode="tv"
elif grep -q '^-- mode: tv$' "$STATE_FILE"; then
    mode="desk"
else
    mode="all"
fi

if [[ "$mode" == "all" ]]; then
    rm -f "$STATE_FILE"
else
    mapfile -t non_tv_outputs < <(list_non_tv_outputs || true)
    {
        printf -- '-- mode: %s\n' "$mode"
        echo "-- Generated by livingroom-mode.sh; loaded by monitors.lua."
        if [[ "$mode" == "tv" ]]; then
            outputs_to_disable=("${non_tv_outputs[@]}")
        else
            outputs_to_disable=("$tv")
        fi
        for name in "${outputs_to_disable[@]}"; do
            quoted_name=$(jq -Rn --arg value "$name" '$value')
            printf 'hl.monitor({ output = %s, disabled = true })\n' "$quoted_name"
        done
    } > "$STATE_FILE"
fi

hyprctl reload >/dev/null
if [[ "$mode" == "tv" ]]; then
    hyprctl dispatch "hl.dsp.workspace.move({ monitor = '$tv' })" >/dev/null
    hyprctl dispatch "hl.dsp.focus({ monitor = '$tv' })" >/dev/null
    echo "livingroom-mode: TV only"
elif [[ "$mode" == "desk" ]]; then
    mapfile -t non_tv_outputs < <(list_non_tv_outputs || true)
    focus_monitor="${non_tv_outputs[0]:-}"
    if [[ -n "$focus_monitor" ]]; then
        hyprctl dispatch "hl.dsp.workspace.move({ monitor = '$focus_monitor' })" >/dev/null
        hyprctl dispatch "hl.dsp.focus({ monitor = '$focus_monitor' })" >/dev/null
    fi
    echo "livingroom-mode: everything except TV"
else
    echo "livingroom-mode: all monitors"
fi
