-- Personal autostart entries. Omarchy's own autostart (the shell, monitor
-- watch, udiskie, first-run provisioning) runs before this file.
--
-- Everything from the old Noctalia-era hypr/config/autostart.conf was
-- deliberately NOT carried over, because Omarchy already provides it:
--
--   noctalia-shell.service          -> omarchy-launch-shell (the bar/notifications/OSD)
--   polkit-gnome-authentication-agent -> shell/plugins/polkit/PolkitAgent.qml
--   wl-paste --watch cliphist       -> the omarchy.clipboard plugin, which keeps its
--                                      own history in ~/.local/state/omarchy/
--                                      clipboard-history.json (SUPER + CTRL + V)
--   scripts/hypridle-power.sh       -> idle.screensaver / idle.lock in
--                                      ~/.config/omarchy/shell.json, with the
--                                      never-suspend-on-AC behaviour enforced by
--                                      /etc/systemd/logind.conf.d/10-kitchen-power.conf
--
-- Add personal entries below, e.g.:
-- hl.on("hyprland.start", function()
--   hl.exec_cmd(o.launch("some-app"))
-- end)

pcall(require, "hypr.omarchy.omarchy-shell")
