-- Generated by omarchy-shell.sh. Re-run that script rather than editing this.
-- The launcher sets OMARCHY_PATH and PATH before exec'ing omarchy-launch-shell,
-- which supervises Quickshell and logs it to the journal under omarchy-shell.
if hyprland and hyprland.exec_on_once then
    hyprland.exec_on_once("/home/alex/.local/bin/omarchy-shell-start")
end
