-- Generated by nwg-displays on 2026-08-14 at 22:53:29. Do not edit manually.

hl.monitor({
    output = "DP-3",
    mode = "2560x1440@143.97",
    position = "2313x0",
    scale = 1.0
})
hl.monitor({
    output = "DP-2",
    mode = "1920x1080@144.0",
    position = "0x139",
    scale = 0.83
})
hl.monitor({
    output = "DP-4",
    mode = "1920x1080@60.0",
    position = "1428x1440",
    scale = 1.0
})
