#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
exec-once = waybar
exec-once = awww-daemon
exec-once = sh -lc 'sleep 1; awww img $HOME/.config/wallpapers/wallpaper.jpg --resize crop --transition-type none'
exec-once = swaync
exec-once = nm-applet --indicator
exec-once = blueman-applet
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = sudo cpupower frequency-set -g performance
