# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                      Colors Configuration                   ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

$active_border = rgb(89b4fa)
$active_border_2 = rgb(74c7ec)
$active_border_3 = rgb(89dceb)
$inactive_border = rgba(45475aaa)
$bg = rgb(1e1e2e)
$fg = rgb(cdd6f4)
$accent = rgb(89b4fa)
