# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Defaults Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛


# General
$mainMod = SUPER
$terminal = kitty
$filemanager = kitty yazi
$browser = firefox
$menu = rofi -show drun
# Screenshots (using grim+slurp — see keybinds.conf)
