-- ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
-- ┃              Monitors — portable across setups              ┃
-- ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
-- Hand-written. NOT generated by nwg-displays anymore — running
-- nwg-displays writes connector-keyed rules to monitors.conf, which
-- this file deliberately ignores. See HOWTO.md ("Monitors").
--
-- Two rules make this work across every machine and desk:
--
--   1. Match on `desc:` (EDID make/model), never on DP-2/DP-3/eDP-1.
--      Connector names describe a *port*, not a *panel* — the same
--      port holds a different monitor at a different desk. Partial
--      matches work, so we omit per-unit serials.
--
--   2. Panels of a known desk get absolute coordinates; everything
--      else falls through to the "auto" catch-all. Relative auto-*
--      placement was tried first and can't express a three-panel
--      arrangement: auto-right measures against the WHOLE layout
--      bounding box (the panel below pushed the right monitor 1920px
--      out, leaving a hole in the row) and auto-center-down centers
--      under one neighbour, not under the row. Absolute coordinates are
--      also independent of Hyprland's monitor placement order, which is
--      the connection order and therefore not knowable from this file.
--
--   3. Bottom-align a row of unequal-height panels rather than
--      top-aligning it, so every panel shares an exact edge with its
--      neighbours. Directional focus across monitors needs exactly
--      aligned edges.
--
-- Rules for panels that aren't plugged in are simply never matched,
-- so every setup can coexist in this one file. Absent panels leave
-- their coordinates unused; the remaining ones don't overlap.

-- Fallback for any display we don't know yet (hotel TV, projector, a
-- laptop panel we haven't captured). Keep this FIRST: specific desc:
-- rules below override it.
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = "auto" })

-- ====== Home desk: absolute layout ======
-- These three are positioned absolutely, on purpose. The relative
-- auto-* directives can't express this arrangement: the portable has
-- to be centered under BOTH upper panels, and auto-center-down centers
-- it under a single neighbour, not under the whole row. Absolute
-- coordinates are also immune to Hyprland's monitor placement order,
-- which is what used to leave a 1920px hole in the top row.
--
-- The layout, in logical pixels:
--
--     x=0             2560       4960
--   y=0 +---------------+--------+
--       |               | (gap)  |
--    90 |   Samsung     +--------+   <- Samsung is the primary
--       |   2560x1440   |  AOC   |
--       |               | 2400   |
--       |               | x1350  |
--  1440 +---------------+--------+
--       |   1520 | portable |    |
--       |        | 1920x1080|    |
--  2520          +----------+
--
-- The row is BOTTOM-aligned (AOC at y=90, not y=0) so all three panels
-- share exact edges at y=1440 — directional focus across monitors needs
-- exactly-aligned edges, and top-aligning would leave the AOC's bottom
-- at 1350 with no shared edge to the portable below.
--
-- If one of these is unplugged its rule simply never matches; the
-- others keep their coordinates and still tile without overlap.

-- ====== Middle ======
-- scale 0.8 is load-bearing: 1920/0.8 = 2400 and 1080/0.8 = 1350, both
-- integers. A fractional scale like 0.83 yields non-integer logical
-- sizes and breaks directional focus across monitors.
hl.monitor({
    output   = "desc:AOC 2460G4",
    mode     = "1920x1080@144",
    position = "2560x90",
    scale    = 0.8,
})

-- ====== Left (primary) ======
-- Samsung Odyssey G5 G53F. Its EDID advertises 60Hz max, which is an
-- under-report — the panel drives far higher. But 200 is past what it
-- holds cleanly: it links up and looks fine on the desktop, then drops
-- frames under load (fullscreen games visibly judder). 144 is stable.
-- Raise only after testing under load, not just checking it lights up.
hl.monitor({
    output   = "desc:Samsung Electric Company LS27FG53x",
    mode     = "2560x1440@144",
    position = "0x0",
    scale    = 1.0,
})

-- ====== Centered below both ======
-- Portable 16" panel. x = 1520 = (4960 - 1920) / 2.
hl.monitor({
    output   = "desc:AOP 16PM1Q",
    mode     = "1920x1080@60",
    position = "1520x1440",
    scale    = 1.0,
})

-- ====== Not yet captured ======
-- These panels ride the catch-all until they're plugged in and
-- captured with `hypr/scripts/capture-monitor.sh`:
--   * the second 1440p panel at the home desk
--   * the laptop's internal display (eDP-1)
