-- Parses monitors.conf (hyprlang), still generated by nwg-displays.
-- Keeps nwg-displays usable without it having to learn Lua output.
local path = (os.getenv("HOME") or "/home/alex") .. "/.config/hypr/monitors.conf"

local f = io.open(path, "r")
if not f then
    hl.monitor({ output = "", mode = "preferred", position = "auto", scale = "auto" })
    return
end

for line in f:lines() do
    local spec = line:match("^%s*monitor%s*=%s*(.+)")
    if spec then
        local name, mode, pos, scale = spec:match("^([^,]+),([^,]+),([^,]+),%s*([^,]+)")
        if name then
            hl.monitor({ output = name, mode = mode, position = pos, scale = scale })
        else
            local dname = spec:match("^([^,]+),%s*disable")
            if dname then
                hl.monitor({ output = dname, disabled = true })
            end
        end
    end
end
f:close()
