-- ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
-- ┃              Monitors — portable across setups              ┃
-- ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
-- Hand-written. NOT generated by nwg-displays anymore — running
-- nwg-displays writes connector-keyed rules to monitors.conf, which
-- this file deliberately ignores. See HOWTO.md ("Monitors").
--
-- Two rules make this work across every machine and desk:
--
--   1. Match on `desc:` (EDID make/model), never on DP-2/DP-3/eDP-1.
--      Connector names describe a *port*, not a *panel* — the same
--      port holds a different monitor at a different desk. Partial
--      matches work, so we omit per-unit serials.
--
--   2. Position relatively (auto-left/right/up/down), never with
--      absolute coordinates. Absolute coordinates leave a hole in the
--      layout when a panel is absent; relative placement closes up
--      over any subset.
--
-- Rules for panels that aren't plugged in are simply never matched,
-- so every setup can coexist in this one file.
--
-- Two hard-won constraints on the positioning — don't undo these:
--
--   * EVERY monitor gets an explicit direction. Never bare "auto".
--     Monitors are placed in Hyprland's internal connection order, not
--     in the order of the calls below, so we can't know which one gets
--     placed first. A direction on the first-placed monitor is a no-op
--     (it anchors at 0x0) and every other monitor then arranges around
--     it correctly. The absolute origin shifts with plug order; the
--     relative arrangement doesn't.
--
--   * Use auto-left/right, NOT auto-center-left/right. The center
--     variants compute against the whole layout's bounding box, which
--     includes the monitor placed below — so the AOC's y jumped from
--     45 to 585 depending on whether the portable was connected first.
--     Plain auto-left/right top-aligns at y=0, which has no cross-axis
--     coupling and gives an exact shared edge (directional focus across
--     monitors needs exactly-aligned edges).

-- Fallback for any display we don't know yet (hotel TV, projector, a
-- laptop panel we haven't captured). Keep this FIRST: specific desc:
-- rules below override it.
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = "auto" })

-- ====== Left of the row ======
-- scale 0.8 is load-bearing: 1920/0.8 = 2400 and 1080/0.8 = 1350, both
-- integers. A fractional scale like 0.83 yields non-integer logical
-- sizes and breaks directional focus across monitors.
hl.monitor({
    output   = "desc:AOC 2460G4",
    mode     = "1920x1080@144",
    position = "auto-left",
    scale    = 0.8,
})

-- ====== Right of the row ======
-- Samsung Odyssey G5 G53F. Its EDID advertises 60Hz max, which is an
-- under-report — the panel drives far higher. But 200 is past what it
-- holds cleanly: it links up and looks fine on the desktop, then drops
-- frames under load (fullscreen games visibly judder). 144 is stable.
-- Raise only after testing under load, not just checking it lights up.
hl.monitor({
    output   = "desc:Samsung Electric Company LS27FG53x",
    mode     = "2560x1440@144",
    position = "auto-right",
    scale    = 1.0,
})

-- ====== Below the row ======
-- Portable 16" panel.
hl.monitor({
    output   = "desc:AOP 16PM1Q",
    mode     = "1920x1080@60",
    position = "auto-down",
    scale    = 1.0,
})

-- ====== Not yet captured ======
-- These panels ride the catch-all until they're plugged in and
-- captured with `hypr/scripts/capture-monitor.sh`:
--   * the second 1440p panel at the home desk
--   * the laptop's internal display (eDP-1)
