-- Parses noctalia-colors.conf (hyprlang), still generated by noctalia-shell
-- on theme changes. Noctalia triggers a reload, which re-runs this file.
local path = (os.getenv("HOME") or "/home/alex") .. "/.config/hypr/noctalia/noctalia-colors.conf"

local vars = {}
local f = io.open(path, "r")
if f then
    for line in f:lines() do
        local k, v = line:match("^%$([%w_]+)%s*=%s*(%S+)")
        if k then vars[k] = v end
    end
    f:close()
end

if vars.primary then
    hl.config({
        general = {
            col = {
                active_border   = vars.primary,
                inactive_border = vars.surface,
            },
        },
        group = {
            col = {
                border_active          = vars.secondary,
                border_inactive        = vars.surface,
                border_locked_active   = vars.error,
                border_locked_inactive = vars.surface,
            },
            groupbar = {
                col = {
                    active          = vars.secondary,
                    inactive        = vars.surface,
                    locked_active   = vars.error,
                    locked_inactive = vars.surface,
                },
            },
        },
    })
end
