# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Variables Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

source = ~/.config/hypr/config/colors.conf

# https://wiki.hyprland.org/Configuring/Variables/\#general
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 3
    col.active_border = $active_border $active_border_2 $active_border_3 45deg
    col.inactive_border = $inactive_border
    resize_on_border = false
    allow_tearing = true
    layout = dwindle


}

# https://wiki.hyprland.org/Configuring/Dwindle-Layout/
dwindle {
    pseudotile = true
    preserve_split = true
}

# https://wiki.hyprland.org/Configuring/Master-Layout/
master {
    new_status = master
}

# https://wiki.hyprland.org/Configuring/Variables/\#misc
misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    vfr = true
    vrr = 0
}
